const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ipc=require('./dist/ipc2581'),{parseCAM}=require('./dist/parser');
function model(){return {name:'測試<&".pcb',version:'6.0',sourceData:{componentRecords:0,footprintRecords:0,netRecords:0},warnings:[],apertures:[{shape:'Round',w:.9,h:.9,rotation:0},{shape:'Oblong',w:2,h:1,rotation:-35},{shape:'Donut',w:2,h:.5,rotation:0},{shape:'Rectangle',w:2,h:1,rotation:90}],layers:[{id:0,name:'COMP',type:4,drills:[],items:[{kind:'pad',x:-1.000002,y:2.000004,aperture:0,flags:0},{kind:'pad',x:2,y:3,aperture:1,flags:0},{kind:'pad',x:3,y:4,aperture:2,flags:0},{kind:'pad',x:4,y:5,aperture:3,flags:0},{kind:'line',points:[[0,0],[1,2],[3,4]],width:.2,fill:0},{kind:'line',points:[[0,0],[1,0],[1,1]],fill:1},{kind:'circle',x:3,y:4,r:2,width:.3,fill:0},{kind:'circle',x:5,y:6,r:1,fill:1}]},{id:2,name:'CMSK',type:4,items:[],drills:[]},{id:6,name:'板邊 & 孔 "圖"',type:4,isDrillDrawing:true,items:[{kind:'pad',x:1,y:2,aperture:0,flags:0},{kind:'line',points:[[0,0],[1,1]],width:.1,fill:0}],drills:[]},{id:9,name:'NC',type:21,items:[],drills:[{x:1,y:2,diameter:1,table:4,tool:2,toolNumber:6,plated:true,designDiameters:[.9]},{x:-1,y:2,diameter:.75,table:4,tool:3,toolNumber:7,plated:false,designDiameters:[]}]}]};}
function validate(out){if(!process.env.IPC2581_SCHEMA)return;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cam-ipc-test-'));try{const f=path.join(dir,'board.xml');fs.writeFileSync(f,out.files[0].data);execFileSync('xmllint',['--nonet','--noout','--schema',process.env.IPC2581_SCHEMA,f],{stdio:'pipe'});}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('IPC-2581C preserves geometry, layer semantics, Unicode names and compensated NC data without inventing design data',()=>{
 const out=ipc.buildExport(model()),xml=out.files[0].data;validate(out);
 assert.match(xml,/revision="C"/);assert.match(xml,/<FunctionMode mode="USERDEF"/);assert.match(xml,/x="-1.000002" y="2.000004"/);assert.match(xml,/rotation="325"/);assert.match(xml,/板邊 &amp; 孔 &quot;圖&quot;/);assert.match(xml,/layerFunction="SOLDERMASK" side="TOP" polarity="NEGATIVE"/);
 assert(!/<(?:Component|Package|Bom|LogicalNet|Profile|Hole|Stackup)\b/.test(xml));assert.equal(out.manifest.layers[2].function,'DOCUMENT');assert.equal(out.manifest.ncReferenceHits,2);assert.equal(out.files.filter(f=>f.name.endsWith('.drl')).length,2);assert.match(out.files.find(f=>f.name.endsWith('_PTH.drl')).data,/T06C1.0/);assert.match(xml,/name="CAMLens:DrawingDiametersMM" type="STRING" value="\[0.9\]"/);assert.equal(out.manifest.drillFiles[0].tools[0].sourceNumber,6);
});
test('IPC selection, roles, drill exclusion and explicit text omission are honored',()=>{
 const m=model();m.layers[0].items.push({kind:'text',text:'unavailable',style:5,x:0,y:0,x2:1,y2:0});assert.throws(()=>ipc.buildExport(m),/字型/);
 const out=ipc.buildExport(m,{layerIds:[0,9],includeText:false,includeDrills:false,roles:{0:'inner_2'},copperLayers:4});validate(out);assert.equal(out.manifest.layers.length,2);assert.equal(out.manifest.layers[0].side,'INTERNAL');assert.equal(out.manifest.omittedTextObjects,1);assert.equal(out.manifest.ncReferenceHits,0);assert.equal(out.files.filter(f=>f.name.endsWith('.drl')).length,0);assert(!out.files[0].data.includes('NC_HIT_REFERENCE'));
});
test('embedded text keeps source text and genuine cutouts, not layer-wide clear polygons',()=>{
 const m=model();m.textStyles={1:{height:2,spacing:0,slant:0,angle:0,alignment:33,mode:4,xScale:1,font:'test'}};m.fonts={test:{ascent:2,descent:0,glyphs:{79:{advance:2,contours:[{kind:'FONTPOLY',points:[[0,0,0],[2,0,0],[2,2,0],[0,2,0],[0,0,0]]},{kind:'FONTVOID',points:[[.5,.5,0],[.5,1.5,0],[1.5,1.5,0],[1.5,.5,0],[.5,.5,0]]}]}}}};m.layers[0].items=[{kind:'text',text:'O',style:1,flags:0,x:1,y:3,x2:3,y2:3}];const out=ipc.buildExport(m);validate(out);assert.match(out.files[0].data,/<Cutout>/);assert.match(out.files[0].data,/CAMLens:SourceText" type="STRING" value="O"/);assert.equal(out.manifest.textObjects,1);
});
test('invalid XML, unknown source records and unsupported geometry block IPC export',()=>{
 let m=model();m.name='bad\u0000name';assert.throws(()=>ipc.buildExport(m),/XML/);m=model();m.sourceData.componentRecords=1;assert.throws(()=>ipc.buildExport(m),/元件/);m=model();m.layers[0].items[4].fill=3;assert.throws(()=>ipc.buildExport(m),/負片/);
 const base='*STATUSB\nMODE Cam\n*END_STATUS\n*LAYERSWID3\n0 COMP 4 0 0 0 0 0\n*END_LAYERS\n*APERTURES1\n10 Round 500000:500000 0 0 NA 0:0 0\n*END_APERTURES\n*PADS\n0 0 0 0 0\n*END_PADS\n';
 for(const [section,key] of [['CMP_LIST','componentRecords'],['FP_LIBRARY','footprintRecords'],['NETS','netRecords']]){const parsed=parseCAM(base+'*'+section+'\nunknown-record\n*END_'+section);assert.equal(parsed.sourceData[key],1);assert.throws(()=>ipc.buildExport(parsed),/未支援/);}
 const empty=parseCAM(base+'*CMP_LIST\n*END_CMP_LIST\n*FP_LIBRARY\n*END_FP_LIBRARY');assert.deepEqual(empty.sourceData,{componentRecords:0,footprintRecords:0,netRecords:0});
});
